/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:7aa72565-b70e-40a9-bdf2-2bfc367e7d41",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_p2CLRKo3q",
    "aws_user_pools_web_client_id": "6lrrr7d21ntsbft7nd22d00ioj",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://4l2wnhg4ovanlnob6e7l25qzra.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
